export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/paths/index',
    'pages/mvp/index',
    'pages/glossary/index',
    'pages/quiz/index',
    'pages/progress/index',
    'pages/news/index',
    'pages/ch1/index',
    'pages/ch2/index',
    'pages/ch3/index',
    'pages/ch4/index',
    'pages/ch5/index',
    'pages/ch6/index',
    'pages/ch7/index',
    'pages/ch8/index',
    'pages/ch9/index',
    'pages/ch10/index',
    'pages/ch11/index',
    'pages/ch12/index',
    'pages/ch13/index',
    'pages/subscribe/index',
  ],
  window: {
    navigationBarBackgroundColor: '#0a0e1a',
    navigationBarTitleText: '大类资产研究',
    navigationBarTextStyle: 'white',
    backgroundColor: '#0a0e1a',
  },
  navigateToMiniProgramAppIdList: [],
})
